# Generated by Django 3.2.19 on 2024-05-20 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carteira',
            old_name='usario',
            new_name='usuario',
        ),
    ]
