# Generated by Django 3.2.19 on 2024-05-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('nome', models.TextField(max_length=50, null=True)),
                ('cpf', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('senha', models.IntegerField(max_length=12)),
            ],
        ),
    ]
