# Generated by Django 3.2.19 on 2024-05-20 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0001_initial'),
        ('transacoes', '0006_auto_20240517_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='carteira',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carteira.carteira'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='hash_transacao',
            field=models.CharField(auto_created=True, max_length=100, unique=True),
        ),
    ]
