# Generated by Django 5.0.6 on 2024-05-22 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0008_remove_customuser_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacao',
            name='hash_transacao',
        ),
    ]
